name: Create Comment on Issues Opened and Testing rebase

on:
  issues:
    types: [opened]
    
jobs:
  comment-with-community-action:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "Dump Github Context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment using community action
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - Doesnt need GITHUB TOKEN
            - With GitHub **Markdown** :sparkles:
            - Used community acton
            - Created by [create-or-update-comment][1]
            
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
          
  comment-with-api:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Creating comment using Github API
        run: |
          gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comment using the GITHUB API
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
      - name: "Printing Secret Token"
        run: echo '${{ toJSON(secrets.GITHUB_TOKEN) }}'
        shell: bash
