name: Create Comment on Issues Opened

on:
  issues:
    types: [opened]
    
jobs:
  comment-with-community-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump Github Context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
